### ISSUE TITLE
Getting Error While Doing Swap

### ISSUE THREAD

**Issue by RFedz007** [justld/dofaker#3]
Hi,

I am getting this below mentioned error in majority of videos.

[  File "D:\dofaker\dofaker\web_ui.py", line 27, in swap_face
    output_path = faker.run(input_path, dst_path, src_path)
  File "D:\dofaker\dofaker\dofaker\face_core.py", line 66, in run
    return self.swap_video(input_path, dst_face_paths, src_face_paths,
  File "D:\dofaker\dofaker\dofaker\face_core.py", line 108, in swap_video
    swapped_image = self.swap_faces(frame,
  File "D:\dofaker\dofaker\dofaker\face_core.py", line 183, in swap_faces
    sim = np.dot(dst_face_embeddings, image_face_embeddings.T)
  File "<__array_function__ internals>", line 200, in dot
ValueError: shapes (1,512) and (0,) not aligned: 512 (dim 1) != 0 (dim 0)]

Pls fix this, as I am not able to process majority of videos due to this error.

Thank You

**Comment by justld** [comment]
It looks like no face detected, you can change an image.

**Comment by justld** [comment]
the src face image should include half human with face.

**Comment by RFedz007** [comment]
Thanks for your quick reply. I closely monitored the process & I figured out that the issue is with the Target face not the source face.

Whenever I do the swap process with target face I get this error.
Whenever I do the swap without Target face the process works smoothly & gives output result without any error.

Can you pls help me to solve this issue.
thank You

**Comment by justld** [comment]
can you provide the image or video?

**Comment by justld** [comment]
I update code now, you can try again.

**Comment by RFedz007** [comment]
Thanks a lot will try again & let you know.

**Comment by RFedz007** [comment]
The issue is been sorted now. It's working properly without any error.
Thank You for looking into this issue & applying a quick fix.
