### ISSUE TITLE
Target Face Not Getting Properly Swapped With The Source Face

### ISSUE THREAD

**Issue by RFedz007** [justld/dofaker#4]
Hi,

I swapped a video using Target face with source face. I observed majority of frames didn't get swapped with the target face. Sometimes face flickers on/off during random frames in a space of 1 sec.

Pls can you test this feature of Target face swap with source, as I think there might be a Face Similarity Threshold issue.

Thank You

**Comment by justld** [comment]
hi, you can use command line to set threshold manually. I will add threshold in gradio web ui tomorrow.
[https://github.com/justld/dofaker/blob/d510b64559434428f7cf99fe4c70d4f041bc6aed/run_faceswapper.py#L58](url)

**Comment by RFedz007** [comment]
> hi, you can use command line to set threshold manually. I will add threshold in gradio web ui tomorrow.
> 
> https://github.com/justld/dofaker/blob/d510b64559434428f7cf99fe4c70d4f041bc6aed/run_faceswapper.py#L58

OK Thanks

**Comment by justld** [comment]
hi， face similarity threshold is added in web ui.
[commit](https://github.com/justld/dofaker/commit/fafc12c39fc4c5e14629774c0db6324af16b104e)

**Comment by RFedz007** [comment]
> hi， face similarity threshold is added in web ui. [commit](https://github.com/justld/dofaker/commit/fafc12c39fc4c5e14629774c0db6324af16b104e)

Thanks a lot. Will check this & let you know by tomorrow.

**Comment by RFedz007** [comment]
Hi,
I tested the face similarity threshold. I have observed that 0.2 looks Good, instead of 0.6 value. Another thing is the swapped face do jump to other face in very small random frames. Yes major issue of (Target Face Not Getting Properly Swapped With The Source Face) has been resolved 70-80%, but still needs some quick small fix. I request you to pls test this Face Similarity Threshold again & after your final testing pls give a default value, as of now 0.6 is not working at all. 0.2 is working, but face flickers/artefacts in small random frames which makes the swap ON/OFF.

This was just my observation.
Thank You

**Comment by justld** [comment]
> Hi, I tested the face similarity threshold. I have observed that 0.2 looks Good, instead of 0.6 value. Another thing is the swapped face do jump to other face in very small random frames. Yes major issue of (Target Face Not Getting Properly Swapped With The Source Face) has been resolved 70-80%, but still needs some quick small fix. I request you to pls test this Face Similarity Threshold again & after your final testing pls give a default value, as of now 0.6 is not working at all. 0.2 is working, but face flickers/artefacts in small random frames which makes the swap ON/OFF.
> 
> This was just my observation. Thank You

Hi, Dofaker is developed based on Insightface and includes two steps: face detection and faceswap, each using an open-source model of Insightface. I guess your situation may be due to the following reasons:
1. The face that needs to be replaced was not detected, and the threshold set was too low, resulting in the replacement of the wrong face;
2. The facial posture is not good (such as sideways), and the similarity with the target face is too low.

I think the following methods can be used to solve this problem:
1. Train new insightface detection and recognition models;
2. Ensure that most of the face is visible.

**Comment by RFedz007** [comment]
> > Hi, I tested the face similarity threshold. I have observed that 0.2 looks Good, instead of 0.6 value. Another thing is the swapped face do jump to other face in very small random frames. Yes major issue of (Target Face Not Getting Properly Swapped With The Source Face) has been resolved 70-80%, but still needs some quick small fix. I request you to pls test this Face Similarity Threshold again & after your final testing pls give a default value, as of now 0.6 is not working at all. 0.2 is working, but face flickers/artefacts in small random frames which makes the swap ON/OFF.
> > This was just my observation. Thank You
> 
> Hi, Dofaker is developed based on Insightface and includes two steps: face detection and faceswap, each using an open-source model of Insightface. I guess your situation may be due to the following reasons:
> 
> 1. The face that needs to be replaced was not detected, and the threshold set was too low, resulting in the replacement of the wrong face;
> 2. The facial posture is not good (such as sideways), and the similarity with the target face is too low.
> 
> I think the following methods can be used to solve this problem:
> 
> 1. Train new insightface detection and recognition models;
> 2. Ensure that most of the face is visible.

Hi,

You know how to train new insightface detection, then pls train. It will be Good from all of us.
Thank You

**Comment by justld** [comment]
Sorry, I do not have a GPU device to train the Insightface detection model, and I cannot guarantee that the trained model is better than the one provided by Insightface. However, I will focus on other open-source models for face detection.

**Comment by RFedz007** [comment]
Hi,

Do you know the procedure how to train new Insightface detection & recognition models. Pls can you tell me from scratch.
How many days/weeks will it take to train
Thank You

**Comment by justld** [comment]
You can find more details in [https://github.com/deepinsight/insightface/tree/master/detection](https://github.com/deepinsight/insightface/tree/master/detection)
